### ISSUE TITLE
Create a captivating video/presentation to showcase all/some of  chispend wallet(crypto/non-crypto) integrations.

### ISSUE THREAD

**Issue by Regedit-msc** [Chimoney/chimoney-community-projects#10]
## What your pr should include?
- Video or slide presentation

## TIPS:
 All left to you and your creativity !!!😁

**Comment by Zaynabnadada** [comment]
Hi, I'll love to work on this please assign it to me, thanks

**Comment by Regedit-msc** [comment]
Sure you can! [Fork](https://github.com/Chimoney/chimoney-api-community-projects/fork) the repo and create a readme to include your submission then open a pr😁.

**Comment by Regedit-msc** [comment]
> Hi, I'll love to work on this please assign it to me, thanks

Sure you can! [Fork](https://github.com/Chimoney/chimoney-api-community-projects/fork) the repo and create a readme to include your submission then open a pr😁.

**Comment by CyberGeni** [comment]
@Regedit-msc or @uchibeke  can multiple people work on this also? if yes, is it possible to get a list of the integrations?

**Comment by Regedit-msc** [comment]
Yes. The integrations are listed on the ChiSpend website.

**Comment by CyberGeni** [comment]
is it the xumm, metamask and chimoney... or the other card with valora, status, bsc evm, eth wallets and binance, coinbase
, luno and edge?

**Comment by Regedit-msc** [comment]
> is it the xumm, metamask and chimoney... or the other card with valora, status, bsc evm, eth wallets and binance, coinbase
> , luno and edge?
> 

Some wallets aren't supported yet.All in the coming soon section.

**Comment by CyberGeni** [comment]
okay... so just to be clear, it's these ones right?  [+ Valora](https://chispend.com/?cSContext=valora)
[+ Status](https://chispend.com/?cSContext=evm)
[+ BSC EVM Wallets](https://chispend.com/?cSContext=evm)
[+ Ethereum Wallets](https://chispend.com/?cSContext=evm)
[+ Polygon Wallets](https://chispend.com/?cSContext=evm)

> Contributor
