### ISSUE TITLE
Create a JS SDK for the Chimoney API

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/chimoney-community-projects#11]
Create a JS SDK for ChiConnect, the new Chimoney API

- Should be installable from a package manager like NPM
- Should have some tests
- Should implement the endpoints outlined at [chimoney.readme.io/reference/introduction](chimoney.readme.io/reference/introduction)

### Resources
- About ChiConnect [chimoney.io/chiconnect](chimoney.io/chiconnect)
- Reference [chimoney.readme.io/reference/introduction](chimoney.readme.io/reference/introduction)
- Swagger Docs [api.chimoney.io/api-docs](api.chimoney.io/api-docs)

# Start here [api.chimoney.io](https://api.chimoney.io/)

**Comment by VoidCupboard** [comment]
Hi! Can I work on this issue?

**Comment by uchibeke** [comment]
Yes @VoidCupboard. I’ll assign you

**Comment by VoidCupboard** [comment]
Thanks!

**Comment by uchibeke** [comment]
So go ahead @Ayo-Awe . What we’d like to see at the end is a package on npm potential called chimoney.js with description, “node sdk for Chimoney’s api by the community. Maintained by @Ayo-Awe”

**Comment by Ayo-Awe** [comment]
Alright, I'll get working on it right away

**Comment by VoidCupboard** [comment]
Wait I'm already working on this and I am mostly done with it (only I need to add tests)

**Comment by uchibeke** [comment]
@VoidCupboard yes. Let’s have multiple implementations. Both submissions will be valid and people can pick what they prefer to use

**Comment by VoidCupboard** [comment]
Ohk, thanks for the confirmation @uchibeke ^-^
