### ISSUE TITLE
There is a minor typo in the README. In the getting started section, the line 1.Fork the Chimoney SDKtoberfest repository.

### ISSUE THREAD

**Issue by collinkip** [Chimoney/chimoney-community-projects#165]
should be corrected to "Hacktoberfest."

**Comment by nandini584** [comment]
heyy it wasn't addressed so i improved it.

**Comment by nandini584** [comment]
[typo: updated to hacktoberfest](https://github.com/Chimoney/chimoney-community-projects/pull/198)

**Comment by priyavratamohan** [comment]
Hi, can you assign this issue to me? Would love to work on it.

**Comment by phyleria** [comment]
Hi @priyavratamohan, 

The issue has already been worked on. I'll close this now
