### ISSUE TITLE
Improve on Chimoney Developer API docs endpoint descriptions

### ISSUE THREAD

**Issue by louis103** [Chimoney/chimoney-community-projects#166]
- [ ] Add more descriptive text on each api endpoint available in the Chimoney Developer API Docs to allow developers understand them better when implementing their applications.

**Comment by adarsh-jha-dev** [comment]
Hey @louis103 could you please assign this issue to me too?

**Comment by louis103** [comment]
Hello Adarsh, this is a small issue and am implementing it already. Please
consider another issue. Thanks.
