### ISSUE TITLE
Making the Login error messages more user friendly and descriptive

### ISSUE THREAD

**Issue by tyke01** [Chimoney/chimoney-community-projects#173]
### Problem:
The current error messages on the login page are not very user-friendly. Specifically, when users provide an invalid email address or password, the error messages are not informative. This can lead to confusion for users trying to sign in.
This is the current error message
`<img width="319" alt="error message" src="https://github.com/Chimoney/chimoney-community-projects/assets/97126661/f6f309ed-c793-439e-a586-9a7a218216c5">`

**Suggested Changes:**
Display more user-friendly messages for common issues, such as invalid email format or incorrect password :

**INVALID EMAIL FORMAT:**
_Current_: `"Firebase: The email address is badly formatted. (auth/invalid-email)."`
_Improved_:` "Please enter a valid email address. Example: [user@example.com](mailto:user@example.com)"`

**INCORRECT PASSWORD:**
_Current_: `"Firebase: The password is invalid or the user does not have a password. (auth/wrong-password)."`
_Improved_: `"Incorrect password. Double-check your password and try again."`

**Comment by phyleria** [comment]
Feedback
