### ISSUE TITLE
Navigation in the CHIMONEY API DOCS

### ISSUE THREAD

**Issue by wachirajoseph** [Chimoney/chimoney-community-projects#175]
The order of the navigation start with :
-Account
-info
-payment
-payouts
-Redeem
-SubAccount
-Wallet

it should start with:
-Introduction
-Getting started with chimoney
-Authenticetion
-knowing the api
-intergreting uninspected
-ping endpoint
-sandbox environment
-libraries & plugins
-webhooks and events

for a person using chimoney API for the first time, to be able to understand how the API works first

**Comment by phyleria** [comment]
Feedback
