### ISSUE TITLE
"Sign in with Google" Button Appears on Both Registration and Login Pages

### ISSUE THREAD

**Issue by tyke01** [Chimoney/chimoney-community-projects#181]
### Description:
_Expected Behavior:_
The "Sign in with Google" button should only be displayed on the registration page, not on the login page. The login button should sign the user in with google immediately without having to go through the registration with google process all over again. 
_Actual behaviour_
Currently, the "Sign in with Google" button is visible on both the registration and login pages, and the user goes through the same process whether its a new registration or a login request.

**Comment by phyleria** [comment]
Feedback
