### ISSUE TITLE
Add a menu for the available products in the book a demo page

### ISSUE THREAD

**Issue by Wainainajoyce** [Chimoney/chimoney-community-projects#183]
-[ ]When booking a demo, there's an option of choosing a product one is interested in. The menu to choose products available when one has already booked the demo.

**Comment by Lymah123** [comment]
@Wainainajoyce , can you put the link to the repo issue?

**Comment by Wainainajoyce** [comment]
@Lymah123, the link is https://chimoney.io/book-a-demo

**Comment by Lymah123** [comment]
Thank you @Wainainajoyce ! Also, can you assign me to do issue ?

**Comment by amyra98** [comment]
Can you please assign me this issue and also add the label hacktoberfest?

**Comment by phyleria** [comment]
Hi all,

Unfortunately I won't be assigning this issue because the code is private.
