### ISSUE TITLE
Improve Devfocus Article 

### ISSUE THREAD

**Issue by ayan-joshi** [Chimoney/chimoney-community-projects#187]
The readme file , which is the only file in the Devfocus Article folder but it's not explaining the the feature properly.
I would like to improve the file with a proper description of the folder.
@phyleria can u assign me this issue I want to work with hacktoberfest label

**Comment by ayan-joshi** [comment]
@phyleria Please have a look

**Comment by phyleria** [comment]
Hi @ayan-joshi 

Can you kindly give me a brief overview of the issue you're trying to work on? Unfortunately, I'm not able to understand it from the description you've provided.

**Comment by ayan-joshi** [comment]
> Hi @ayan-joshi
> 
> Can you kindly give me a brief overview of the issue you're trying to work on? Unfortunately, I'm not able to understand it from the description you've provided.

yes , the readme file of the devfocus article folder submissions/Dev focused articles should be improved , it's just have 2 lines of explanation and takes us to medium article , 
It should explain the purpose more precisely so I would like to work on it and improve the file @phyleria

**Comment by phyleria** [comment]
Ok, go ahead.
