### ISSUE TITLE
Create a Python Package for the Chimoney's API

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/chimoney-community-projects#19]
Create a Python Package for ChiConnect, the new Chimoney API

- Should be installable from a package manager like PIP
- Should have some tests
- Should implement the endpoints outlined at [chimoney.readme.io/reference/introduction](chimoney.readme.io/reference/introduction)

### Resources
- About ChiConnect [chimoney.io/chiconnect](chimoney.io/chiconnect)
- Reference [chimoney.readme.io/reference/introduction](chimoney.readme.io/reference/introduction)
- Swagger Docs [api.chimoney.io/api-docs](api.chimoney.io/api-docs)

# Start here [api.chimoney.io](https://api.chimoney.io/)

**Comment by thelimeskies** [comment]
Hi,

I Handled this and I've made a PR Containing the project and Documention(Remains Deployment to pip and any minor issue which I haven't discovered yet.)
