### ISSUE TITLE
Fix Code of Conduct 

### ISSUE THREAD

**Issue by amosayomide05** [Chimoney/chimoney-community-projects#190]
Code of Conduct link is directing to a 404 error page

Please add hacktoberfest label to this

**Comment by amosayomide05** [comment]
I made a PR with the fix #185

**Comment by Shashankpantiitbhilai** [comment]
assign it to me please

**Comment by phyleria** [comment]
Hi @Shashankpantiitbhilai 

This has already been worked on. Thanks
