### ISSUE TITLE
Build Chimoney Whatsapp Bot

### ISSUE THREAD

**Issue by amosayomide05** [Chimoney/chimoney-community-projects#197]
Anyone in a whatsapp group should be able to send Chimoney to other users using `/chimoney_pay @user amount`

**Comment by amosayomide05** [comment]
@phyleria Please assign me to this and add hacktoberfest label to it. THANKS

**Comment by amosayomide05** [comment]
@phyleria Please assign me to this and add hacktoberfest label to it. THANKS

**Comment by phyleria** [comment]
Done.

**Comment by onyangoju** [comment]
Create a banner for issue #197

**Comment by onyangoju** [comment]
Please assign me to create a banner for issue #197

**Comment by phyleria** [comment]
Hi @onyangoju 

There's no need for a banner on this issue

**Comment by FloatinggOnion** [comment]
@phyleria can more than one person be assigned to an issue?

**Comment by phyleria** [comment]
Hi @amosayomide05 

Do you need help on this issue?

**Comment by amosayomide05** [comment]
> Hi @amosayomide05 
> 
> Do you need help on this issue?

No, I'm still working on it

**Comment by phyleria** [comment]
Ok, thanks for the feedback
