### ISSUE TITLE
Create a flutter wrapper/widget package for ChiSpend marketplace.

### ISSUE THREAD

**Issue by Regedit-msc** [Chimoney/chimoney-community-projects#21]
- As a developer, I can install ChiSpend  from pub.dev( I don't need to implement the web view). 
- The package/Widget should provide easy options to customise the market place using [customisation](https://github.com/Chimoney/chispend-integration-examples/tree/main/web#customizing-chispend) properties supported by ChiSpend.
-  [Pay With Wallet](https://github.com/Chimoney/chispend-integration-examples/tree/main/web#-external-wallet-integration) that's available through the `ChiSpendChannel` JavaScriptChannel should be abstracted into a callback that's available on the widget.

[More references](https://github.com/Chimoney/chispend-integration-examples/tree/main/widget)

**Comment by dynamic-Somto** [comment]
Hi,  please I'll like to take it up. Please assign it to me
