### ISSUE TITLE
 update readMe from  "Chimoney Hacktoberfest 2023" to " Chimoney Community Project"so that contributors can make their contributions at any given time of the year.

### ISSUE THREAD

**Issue by devmulumia** [Chimoney/chimoney-community-projects#215]
I request to update "Chimoney Hacktoberfest 2023" to " Chimoney Community Project" so that contributors can make their contributions at any given time of the year.

**Comment by kherld-hussein** [comment]
@phyleria Please assign me to this. THANKS
