### ISSUE TITLE
Write detailed content for new contributors explaining how to contribute to Chimoney community project issues. 

### ISSUE THREAD

**Issue by elegant1T** [Chimoney/chimoney-community-projects#22]
This is a good first issue. 
- Issues under the Chimoney community project are open to all levels of contributors. Write a step-by-step article to explain the A-Z steps to contribute to this project.
Content can be in any format _(articles, demo videos, Tiktok videos, or anyone you can think of)_.
- All issues under this project are focused on [Chi Connect](https://chimoney.io/chiconnect) and [Chi Spend](https://chispend.com/). 
- Do include more resources that will benefit your reader. 

Chimoney Community project: [https://github.com/Chimoney/chimoney-api-community-projects](https://github.com/Chimoney/chimoney-api-community-projects)
Chi Connect Documentation: [https://chimoney.readme.io/reference/introduction](https://chimoney.readme.io/reference/introduction)
Chimoney Blog: [https://chimoney.io/blogs](https://chimoney.io/blogs)
Chimoney on TikTok: [https://www.tiktok.com/@chimoney.io/video/7149193982319267077?is_copy_url=1&is_from_webapp=v1&item_id=7149193982319267077](https://www.tiktok.com/@chimoney.io/video/7149193982319267077?is_copy_url=1&is_from_webapp=v1&item_id=7149193982319267077)

**Comment by ErebusXAbyss** [comment]
I would like to work on this issue

**Comment by Elozzy** [comment]
@ErebusXAbyss  it has already been worked on.  More article issues would be added soon.
