### ISSUE TITLE
Arrangement customization of the contents of the left side-navigation bar in the Chimoney documentation. ('CHIMONEY API contents ' can start from the top  followed by 'CHIMONEY API DOCS' )

### ISSUE THREAD

**Issue by ShadrackMwema** [Chimoney/chimoney-community-projects#224]
The contents of 'CHIMONEY API' , that is Introduction, Getting started with Chimoney API etc. will give a better look to the website if they start from top in the side-navigation bar followed by 'CHIMONEY API DOCS and its content: Account, Info etc.'
This issue is like a recommendation to developers.

**Comment by equatorCF** [comment]
@phyleria assign this task to me. Wanna give it a try.

**Comment by phyleria** [comment]
Feedback
