### ISSUE TITLE
Design an attractive banner for the hacktober fest highlighting the issues it deals with

### ISSUE THREAD

**Issue by its-AlexNjau** [Chimoney/chimoney-community-projects#226]

**Comment by Kelvin2544** [comment]
I think thats a good idea..You definitely should try that.

**Comment by occupyashanti** [comment]
Its a  good idea

**Comment by ghost237-sys** [comment]
@phyleria assign this to me

**Comment by Kelvin2544** [comment]
@ghost237-sys  is good at this field @phyleria.He should give it a try.

**Comment by onyangoju** [comment]
@phyleria please assign me this issue

**Comment by sherlyn-kalondu** [comment]
@its-AlexNjau  Assign this to me
