### ISSUE TITLE
create a attractive hacktober fest banner highlighting what it is really about   

### ISSUE THREAD

**Issue by StephenMatei** [Chimoney/chimoney-community-projects#229]

**Comment by onyangoju** [comment]
Please assign me this issue

**Comment by StephenMatei** [comment]
@onyangoju has been assigned

**Comment by phyleria** [comment]
Hi @onyangoju 

We already have a banner in the `images` folder. Kindly add it

**Comment by onyangoju** [comment]
![chimoney hacktoberfest 2023](https://github.com/Chimoney/chimoney-community-projects/assets/147000453/2ec83f08-599b-48c3-a2e7-9f5d53980a77)

**Comment by phyleria** [comment]
Hi @onyangoju 

We have a hacktoberfest banner as I had mentioned previously that you can add.

**Comment by DecentralizAI** [comment]
Can I also be assigned this issue?
