### ISSUE TITLE
Chimoney API documentation "left side-bar contents' customization"

### ISSUE THREAD

**Issue by equatorCF** [Chimoney/chimoney-community-projects#237]
Anyone  visiting the API Documentation site should first navigate through the API Contents and then to creating account.

**Comment by phyleria** [comment]
Hi @equatorCF 

Can you kindly provide more description of what you would like to implement?

**Comment by equatorCF** [comment]
Anyone visiting the API Documentation page should first learn how Chimoney API contents then to Chimoney API Docs
