### ISSUE TITLE
MapBox/Google Maps x Chimoney: Show Chimoney supported products/countries in a map

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/chimoney-community-projects#24]
Build a one-page website with any web framework or plain JS that shows Chimoney's products on a map

- Use the [/assets-info endpoint ](https://chimoney.readme.io/reference/get_v0-2-info-assets)to pull the products
- Render products in map using the country info that is included in the object

Stretch goal:
- Make this a general map of supported Payout methods for countries so that Developers, Remote employers and anyone can use this as a reference to see what options they can pay people with. So, they search by country and see the options people in that country can accept

**Comment by motasimmakki** [comment]
I would like to work on this issue, but I also need your help to get started, could you help me out with it?

**Comment by tobiadiks** [comment]
This look interesting and I'll work on this.
I just help in understanding the issue better.

**Comment by uchibeke** [comment]
Sure.

so the assets info endpoint returns an array of payout methods (MTN mobile money, Bitcoin, Ghana bank, Amazon US gift card, etc). Each payout method contains an array of countries that method works in or empty, if it works globally 

Use this info to display the items on a map such that a payout method is placed in the countries in the that it is supported in

**Comment by uchibeke** [comment]
And the stretch goal is to extend this to work with more than just one payout provider, like Chimoney. To make this work, you might need to pull the data from chimoney and enrich it with a provider field=chimoney and then rendering as before but with option to filter by provider

To add a new provider, look at a different service like Tremendous or another platform for getting payed and get their list of countries and methods and also render it

end result is a beautiful searchable map of the best way businesses can pay people globally 

Forget stretch goal for now but that’s the long-term goal

**Comment by tobiadiks** [comment]
Ok that's sounds clearer. Can I be assigned to this issue?

**Comment by tobiadiks** [comment]
I'll be using Mapox

**Comment by uchibeke** [comment]
Will do

@tobiadiks let me know if you still want to do it and maybe you could
- use any other  framework
- google maps
- use a different approach

All submissions will be valid

**Comment by tobiadiks** [comment]
Thanks @uchibeke 
Will be using

Next JS and Mapox

**Comment by uchibeke** [comment]
Sounds great!

**Comment by tobiadiks** [comment]
Yes, I saw that difference earlier on from the documentation. I'll.
