### ISSUE TITLE
Customize the readme file

### ISSUE THREAD

**Issue by Ajiboso-Adeola** [Chimoney/chimoney-community-projects#252]
Add the Chimoney logo to the readme file

Add the Twitter link 🖇️ to the mode of  Communication in the Readme file

In addition help structure issue in a way where contributors can easily find issue relating to their interest quickly  article, API, design

Hi @phyleria, if the issue is acceptable. I would like to work on it.

Please assign me.

**Comment by Lymah123** [comment]
Hi @Ajiboso-Adeola , are you intending to work on it? If no, you can assign it to me.

**Comment by phyleria** [comment]
Hey @Ajiboso-Adeola 

Please go ahead.

**Comment by priyavratamohan** [comment]
Hi! If the task hasn't been completed, can you please assign it to me, would love to do it
