### ISSUE TITLE
Hamburger Menu Issue

### ISSUE THREAD

**Issue by mozi47** [Chimoney/chimoney-community-projects#254]
When you click on the hamburger menu without closing the menu and expanding the browser size, the menu is still shown.

1. Visit this page https://chimoney.io/
2. Shrunk the browser to below 1024px
3. Click on hamburger menu
4. Expand the browser, width greater than 1024px

Video:
https://github.com/Chimoney/chimoney-community-projects/assets/20722868/d0c0cc58-3399-45a3-92c6-614fe6c97774

Screenshot:
![image](https://github.com/Chimoney/chimoney-community-projects/assets/20722868/63fcbe0f-5d45-4aa3-a212-898cf5ba8fae)

Could I be assigned to this issue? I'd be happy to work on this and submit a pull request.

**Comment by Rasheed124** [comment]
Alright. I will be expecting @mozi47 .

**Comment by phyleria** [comment]
Hi all,

Unfortunately I won't be assigning this issue because the code is private.

**Comment by Rasheed124** [comment]
Alright. Thanks
