### ISSUE TITLE
Enhance chispend presentation readme file 

### ISSUE THREAD

**Issue by ayan-joshi** [Chimoney/chimoney-community-projects#258]
The chispend presentation readme file explains us about the integration of the wallet with just showing a single image and taking us to canva to explain with 5 slides . 

I would like to enhance the readme I will explain the whole integration of wallet part in the readme by adding all needed images and their information below it as well.

If you like my idea please assign me the issue @phyleria

**Comment by ayan-joshi** [comment]
@phyleria please have a look

**Comment by phyleria** [comment]
Hi @ayan-joshi,

All the suggestions on the presentation have already been implemented so this issue might be irrelevant.
But there are names that should be updated i.e `Chispend` to `Unispend`. I'll create an issue on that and you can claim it.

**Comment by phyleria** [comment]
Here's the issue @ayan-joshi 

https://github.com/Chimoney/chimoney-community-projects/issues/267

**Comment by ayan-joshi** [comment]
> Here's the issue @ayan-joshi
> 
> #267

Thanks I have messaged there u can assign it
