### ISSUE TITLE
Unnecessary Repetition Of Chimoney Payout Airtime Background

### ISSUE THREAD

**Issue by faria-karim-porna** [Chimoney/chimoney-community-projects#261]
**Issue:** Showing the background gradient of chimoney payout airtime project repetitively.
![chimoneyRepetitiveBackground](https://github.com/Chimoney/chimoney-community-projects/assets/67676724/5ca53cd2-6dfc-4e94-9179-1b6c3c1389b5)
**Reason to fix:** For better visual and user interface.

**Comment by faria-karim-porna** [comment]
Hey @phyleria would you please assign this issue to me? I want to work on this.

**Comment by phyleria** [comment]
Hi @faria-karim-porna 

Can you provide more details on this, where did you experience it?

**Comment by phyleria** [comment]
OK, go ahead.

**Comment by faria-karim-porna** [comment]
@phyleria would you please label it as "hacktoberfest"?

**Comment by phyleria** [comment]
Done
