### ISSUE TITLE
Adding A New Section "Project Setup" In The Readme File

### ISSUE THREAD

**Issue by faria-karim-porna** [Chimoney/chimoney-community-projects#262]
**Issue:** There is no section like "Project Setup" in the readme file.
**Way to fix:** This section will contain the link to the readme files of all the individual projects.
**Reason to fix:** So that people do not get confused to set up their preferred project.

**Comment by faria-karim-porna** [comment]
Hello @phyleria would please assign this task to me?

**Comment by phyleria** [comment]
Ok, go ahead
