### ISSUE TITLE
Fixing typos found in README.md file

### ISSUE THREAD

**Issue by sh4d0wy** [Chimoney/chimoney-community-projects#264]
Hi there! 

I noticed a few typos in the 'submissions/chisend/Readme.md' file that I'd like to bring to your attention:

1. In the 19th line, there's a small typo: "ammount" should be "amount."
2. Near the end of the file, at lines 69 and 79, "Intergerate" should be corrected to "Integrate."

These minor errors can affect the clarity and professionalism of your project's documentation. Therefore, I thought it would be helpful to point them out. 

I'm happy to contribute to the project and help improve the documentation. #256

**Comment by SamsShow** [comment]
I've already fixed the issue in #266 please assign it to me
