### ISSUE TITLE
[docs]: Invalid link to MIT LICENSE in README.md

### ISSUE THREAD

**Issue by adarsh-jha-dev** [Chimoney/chimoney-community-projects#278]
While going through the README.md ,i came across this docs typo. The link  to the LICENCE.md file provided in the README.md is not a valid hyperlink. I have attached the screenshot of the same : 

![Screenshot 2023-10-23 165610](https://github.com/Chimoney/chimoney-community-projects/assets/132337675/787d951f-0a11-49d9-9016-58b358f4521d)

##Expected Behaviour 
It should take me to the LICENSE.md file

##Actual Behaviour 
The page is giving 404 error

**Comment by adarsh-jha-dev** [comment]
Sorry to bother but, @phyleria , i have raised a PR #279 for this issue too. Could you please just have a look at it and merge if you're satisfied ?

**Comment by JAkrish29** [comment]
Hello Could you please assign me this issue ??

**Comment by adarsh-jha-dev** [comment]
> Hello Could you please assign me this issue ??

Hey @JAkrish29 , I don't have permissions to assign issues and also I have already raised a PR for the same. So look for some other issues , there are better ones.
