### ISSUE TITLE
Request to Update Twitter Logo in Footer Section

### ISSUE THREAD

**Issue by moheyt** [Chimoney/chimoney-community-projects#282]
I have identified that the Twitter logo displayed in the footer section of website is outdated, and it is crucial to keep branding up to date with the latest elements provided by Twitter.

![Screenshot 2023-10-24 213041](https://github.com/Chimoney/chimoney-community-projects/assets/85775976/9799c32e-61dc-4c6c-b279-06f4c3ccbbf1)

**Comment by moheyt** [comment]
I would like to work on this. Can you assign it to me?

**Comment by ashutuptiwari** [comment]
If @moheyt removes his assignment in the future, assign this to me. Emphasis on 'if'

**Comment by phyleria** [comment]
Hi @moheyt 

That codebase is also privately maintained.
