### ISSUE TITLE
BUG: Invalid href in next/router

### ISSUE THREAD

**Issue by moheyt** [Chimoney/chimoney-community-projects#283]
Description
When attempting to navigate to a URL using the next/router library, an error is encountered. The error message indicates that the href being passed to the router is invalid due to repeated forward slashes (//) or backslashes (). The problematic URL is https://chimoney.io/blogs/introducing-chimoney-for-startups-to-provide-ap-is-and-payouts-for-early-stage-startups.

![Screenshot 2023-10-24 213639](https://github.com/Chimoney/chimoney-community-projects/assets/85775976/7ae3ff75-364f-42a7-9bd4-007a5ecd5e42)

Steps to Reproduce
1. Use the next/router library in a Next.js project.
2. Attempt to navigate to the URL https://chimoney.io/blogs/introducing-chimoney-for-startups-to-provide-ap-is-and-payouts-for-early-stage-startups.

Expected Behavior
The router should navigate to the specified URL without any errors.

Actual Behavior
An error message is encountered, which states that the href passed to next/router is invalid due to repeated forward slashes (//) or backslashes ().

Possible Solutions
1. Check the structure and validity of the URL https://chimoney.io/blogs/introducing-chimoney-for-startups-to-provide-ap-is-and-payouts-for-early-stage-startups. Ensure that it doesn't contain any repeated forward slashes or backslashes.
2. If the issue is related to the Next.js or router version being used, consider updating to the latest version to see if the problem is resolved.
3. Review the code where the URL is being passed to next/router to ensure there are no accidental double slashes in the URL.

**Comment by moheyt** [comment]
I would like to work on this. Can you assign it to me?

**Comment by ashutuptiwari** [comment]
If @moheyt removes his assignment in the future, assign this to me. Emphasis on 'if'

**Comment by phyleria** [comment]
Hi @moheyt 

The codebase of the site is private so I can't assign it to you but I'll forward it as feedback. Thanks
