### ISSUE TITLE
[Feature]: Add support for sandbox mode in JavaScript SDK

### ISSUE THREAD

**Issue by Ayo-Awe** [Chimoney/chimoney-community-projects#289]
Sandbox mode support for the chimoney JavaScript SDK will allow developers test their apps against the Chimoney Sandbox API

**Comment by Ayo-Awe** [comment]
@phyleria  Can I work on this issue and could you add a  hacktoberfest label to it

**Comment by uchibeke** [comment]
> @phyleria Can I work on this issue and could you add a hacktoberfest label to it

Yes. go ahead
