### ISSUE TITLE
Not Navigating To The Specific Section Of The Readme File

### ISSUE THREAD

**Issue by faria-karim-porna** [Chimoney/chimoney-community-projects#298]
**Issue:** Clicking on any of the links of sections under Table of Contents is not navigating to the section which I have clicked.
![navigate](https://github.com/Chimoney/chimoney-community-projects/assets/67676724/1e740ce8-59a3-457c-9ff6-b64f6a881ea2)
**Reason to fix:** For easiness to navigate to a particular section from Table of Contents.

**Comment by faria-karim-porna** [comment]
Hello @adebayoileri @phyleria would you please assign this issue to me?

**Comment by vinfinity7** [comment]
Hello @adebayoileri  @phyleria assign this issue to me?

**Comment by faria-karim-porna** [comment]
Hello @phyleria there was some emojis before the title of each section. But now some sections has emojis and some sections does not. Are they removed intentionally or unintentionally?

**Comment by phyleria** [comment]
Hi @faria-karim-porna 

That was intentional but I realised not all of them have been removed. While working on this issue's changes can you also remove the rest of the emojis for formality. Thanks

**Comment by faria-karim-porna** [comment]
@phyleria Got it. But I think after removing the emojis from the rest of the sections, the issue will be fixed automatically. I don’t have to do anything extra. Should I go ahead?

**Comment by phyleria** [comment]
Yes, sure
