### ISSUE TITLE
Implement a simple redeem flow project with ChiConnect API

### ISSUE THREAD

**Issue by Elozzy** [Chimoney/chimoney-community-projects#3]
## Implement one of the following redeem flow

- Redeem [airtime](https://chimoney.readme.io/reference/post_v0-2-redeem-airtime)
-  Redeem [Chimoney](https://chimoney.readme.io/reference/post_v0-2-redeem-chimoney)
-  Redeem [gift card](https://chimoney.readme.io/reference/post_v0-2-redeem-gift-card)
-  Redeem [Mobile Money](https://chimoney.readme.io/reference/post_v0-2-redeem-mobile-money)

**Comment by mzoyinda** [comment]
Hi, I would like to work on this project. Assign me to this.

**Comment by Elozzy** [comment]
okay

**Comment by mzoyinda** [comment]
@elozzy, can i implement the rest??

**Comment by Elozzy** [comment]
> @Elozzy, can i implement the rest??

yeah Sure, you can @mzoyinda. Just Create an issue per implementation.

**Comment by mzoyinda** [comment]
yaaayyyhhh.. Thanks!
