### ISSUE TITLE
feat:one-platform to send payouts

### ISSUE THREAD

**Issue by Davidongora** [Chimoney/chimoney-community-projects#307]
### Description

one platform that the user can Redeem airtime, chimoney , mobile money and get details of his/her wallets .
it also allows one to send giftcards, airtime 
i plan to use this endpoints
Payout airtime.
POST
https://api.chimoney.io/v0.2/payouts/airtime
Payout mobile-money.
POST
https://api.chimoney.io/v0.2/payouts/mobile-money
Payout giftcards.
POST
https://api.chimoney.io/v0.2/payouts/gift-card
Get single wallet details.
POST
https://api.chimoney.io/v0.2/wallets/lookup

### Ready to Work?

- [X] I want to work on this issue

**Comment by phyleria** [comment]
Hi @Davidongora 

I believe this is the Chimoney platform you would want to recreate, We currently have these features
