### ISSUE TITLE
Bug: Chimoney Payout Airtime Is Not Fully Responsive

### ISSUE THREAD

**Issue by faria-karim-porna** [Chimoney/chimoney-community-projects#314]
### Description

**Issue**: The app is not fully responsive.
**Reason to fix:** For better user experience across all devices.

### Screenshots

![airTimeNotResponsive](https://github.com/Chimoney/chimoney-community-projects/assets/67676724/c5d3a04f-b91d-4a1f-bff6-8d772b911e1d)

### What browsers are you seeing the problem on?

Chrome

### Ready to Work?

- [X] I want to work on this issue

**Comment by faria-karim-porna** [comment]
Hello @phyleria Would you please assign this issue to me?

**Comment by phyleria** [comment]
Ok
