### ISSUE TITLE
Enhancement: Github Bot enhancements

### ISSUE THREAD

**Issue by uchibeke** [Chimoney/chimoney-community-projects#335]
### Description

- Increase max amount to $100
- First message should be `@maintainer, PR merged. Please send a chimone.io reward to @contributor`
- Update payment link message to 
```
@maintainer, you have initiated a reward payment of $Amount using the Chimoney GitHub bot.

Please, click on the payment link to complete the Payment using Chimoney.
```
- Confirm how the emails work: Are you able to get the emails of the contributors to be able to send them the reward?

### Ready to Work?

- [ ] I want to work on this enhancement

**Comment by uchibeke** [comment]
@Ayo-Awe could you please work on this enhancement?

**Comment by Ayo-Awe** [comment]
@uchibeke I'll work on it and push the changes today.

I also have plans to push the updates for payment notification, but that'll be after HacktoberFest.

**Comment by Ayo-Awe** [comment]
* The bot gets the emails for the contributor's public GitHub profile. 

* If the contributor doesn't have one, the bot will respond with an error message `Unable to retrieve contributor's email`. 

* You can check if a contributor has a public email by visiting their GitHub profile page i.e `https://github.com/<username>`
