### ISSUE TITLE
Enhancement: Chimoney GitHub Bot - Retrieve Contributor Email from Payment Profile

### ISSUE THREAD

**Issue by phyleria** [Chimoney/chimoney-community-projects#363]
### Description

Currently, the [Chimoney GitHub](https://github.com/Chimoney/chimoney-community-projects/tree/main/submissions/chimoney-github-bot) bot allows contributors to be paid directly once their PR is merged. The process works as follows:
- When a PR is merged, the bot notifies the maintainer.
- The maintainer writes the command `/payout 25` in the PR comment section.
- A payment link is generated, and when the maintainer clicks on the link, they are prompted to pay the contributor via their Chimoney wallet. 
- Once accepted, the payment is sent to the contributor’s email.

### Problem:
One limitation we encountered was that if a contributor’s email was not public on GitHub, the bot could not send the payment.

### Proposed Solution:
We want to enhance the bot by ensuring that if a contributor’s email is not public on GitHub, the bot will retrieve the email from their Chimoney Payment Profile instead. You can use the following endpoint to retrieve the email from the payment profile:

- [Chimoney API Endpoint](https://chimoney.readme.io/reference/post_v0-2-accounts-public-profile-1): `POST /v0.2/accounts/public-profile`

### Steps for Implementation:
1. Modify the existing Chimoney GitHub bot to:
   - Check if the contributor’s email is public on GitHub.
   - If the email is not public, retrieve it from the contributor’s Chimoney Payment Profile using the provided API endpoint.
   - Ensure that contributors are prompted to create a Chimoney Payment Profile if they haven't.
   - Once the email is retrieved the payout is sent automatically

### Ready to Work?

- [ ] I want to work on this enhancement

**Comment by Het4304** [comment]
I want to work on this enhancement @phyleria @adebayoileri
