### ISSUE TITLE
Enhancement: Add Interledger Payment Pointer Support in Chimoney GitHub Bot

### ISSUE THREAD

**Issue by phyleria** [Chimoney/chimoney-community-projects#364]
### Description

Currently, the [Chimoney GitHub bot](https://github.com/Chimoney/chimoney-community-projects/tree/main/submissions/chimoney-github-bot) allows contributors to be paid directly once their PR is merged via their email. By default, the payment is sent to the contributor's email associated with their Chimoney Payment Profile.

### Proposed Enhancement:
We want to expand the functionality of the Chimoney GitHub bot by allowing contributors to be paid via their Interledger payment pointer, which can be retrieved from their Chimoney Payment Profile. 

### Steps for Implementation:
1. Modify the Chimoney GitHub bot to:
   - Retrieve the contributor's Interledger payment pointer from their Chimoney Payment Profile if available.
   - Allow maintainers to choose whether to pay a contributor via their email (default) or via their Interledger payment pointer. 
   - Add a new command for payment via Interledger, such as `/payout 25 ilp` to trigger payment via Interledger.
   - If the contributor has an Interledger payment pointer in their profile, the bot will process the payment using the pointer instead of email.

### API Endpoint to Use:
- [Chimoney API Endpoint](https://chimoney.readme.io/reference/post_v0-2-accounts-public-profile-1): `POST /v0.2/accounts/public-profile`

### Expected Outcome:
- Contributors will have the option to receive payments via their Interledger payment pointer.
- Maintainers can choose between paying via email or Interledger payment pointer by issuing appropriate commands.

### Ready to Work?

- [ ] I want to work on this enhancement

**Comment by s-vamshi** [comment]
@phyleria @adebayoileri i would like to work on this
