### ISSUE TITLE
proposed changes for chispend website

### ISSUE THREAD

**Issue by CyberGeni** [Chimoney/chimoney-community-projects#38]
# **landing page**
current look on 13inch laptop full screen
![image](https://user-images.githubusercontent.com/70205370/194720372-1c9193ca-fc0b-4567-aad7-4c80734a0856.png)

## new proposed look
![image](https://user-images.githubusercontent.com/70205370/194720520-e9e9d4f9-4ef6-4621-831f-4df2f37c2e8d.png)

##reason for change

- I think whatever screen size the user is using, the hero content should always be at the middle of the screen. currently, it looks like the dev used a top margin to place the hero text away from the header. that could be substituted for using flex display and a screen height of 100vh so that on whatever height of device, the hero remains at the center of the screen.

# **chispend features section**
current look on a slightly large screen
![image](https://user-images.githubusercontent.com/70205370/194720876-21c3c05e-c9b7-4c62-b478-bdbe7967f9cd.png)

## new proposed look 
(photo reference not available)

## reason for change
- i feel the whole feature section should have a max-width, so that when the screen gets wider, the space between doesn't get too much to make it look weird/deserted just like in the photo

# **web applications grid**
## current look
![image](https://user-images.githubusercontent.com/70205370/194722355-b5f09a4b-d043-4612-aad5-23f0d29701c1.png)
- the grid gap isn't consistent

## proposed change
(photo reference unavailable)

- the text size of labels should be the same size
- the text size of the applications coming soon and other apps should be reduced
- the grid gap should be consistent

## reason for change
- both the 'coming soon' and 'live' texts are labels, and I think it would make more sense if the text were same size.
- for the 'other apps' and 'coming soon' section, I think the text size of the items should be reduced to base text because it looks.. off. i get why it is big is prpbably because y'all wanted the sizes of the containers to be consistent and that's valid. but that also makes the text size inconsistent, which i think causes more harm. what i think can be done is to reduce the text size, and it might make the 'xumm wallet' section look less odd. i wanted to propose a change for that section too, but i have no idea what it can be changed to I just know it looks odd.

# read the docs button
## current look 
![image](https://user-images.githubusercontent.com/70205370/194723147-76e107c3-1318-4659-ad7d-06753dd407e8.png)
## proposed look
![image](https://user-images.githubusercontent.com/70205370/194723251-bfc4b946-3d03-42c1-9db0-9ecf78f5c045.png)
## reason for change
- it simply looks better

# user experience section
## current look
(page too large to screenshot all section)

## proposed change
i get what y'all were trying to achieve, and it is a veryyy nice idea. the whole random arrangement design makes sense. but i think it can look better than it looks now. should i say it should look more... randomly organised? i guess. y'all can follow a random but probably more organised pattern in displaying the grids. again i do not have a visual proposed layout, so you can just go ahead and ignore that part for now :)

okay bye

**Comment by MUCCHU** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by Elishaokon13** [comment]
@uchibeke Good day, I would love to take this issue.

Please you can assign it to me while I commit my changes.
Thank you

**Comment by adi-uchiha** [comment]
Where is the source code of the website ?

**Comment by CyberGeni** [comment]
i don't know, i don't think it's on a public repo

**Comment by adi-uchiha** [comment]
Mmm.. if it's not public. How can we contribute ?

**Comment by CyberGeni** [comment]
i just created an issue that i found, i'm a contributor too not a maintainer

**Comment by Regedit-msc** [comment]
Fixed!

**Comment by CyberGeni** [comment]
@Regedit-msc thanks
