### ISSUE TITLE
Bug: Broken Link in Integrating-Unispend

### ISSUE THREAD

**Issue by ayan-joshi** [Chimoney/chimoney-community-projects#393]
### Description

![image](https://github.com/user-attachments/assets/1c6f3ebf-f84d-43dd-89ec-4da37cf40fb8)

Here the link `redeemAny` is broken in Integrating-unispend , I would like to fix the link. 

have a look at this @phyleria 

### Ready to Work?

- [X] I want to work on this issue

**Comment by phyleria** [comment]
Hi @ayan-joshi 

Thanks so much for noting this. I have fixed this on our end as the API docs editing is not public. 

I'll close this issue for now, and you'll get a badge for it. Thanks

**Comment by phyleria** [comment]
Hi @ayan-joshi

Thanks so much for noting this. I have fixed this on our end as the API docs editing is not public.

I'll close this issue for now, and you'll get a badge for it. Thanks

**Comment by ayan-joshi** [comment]
okay thanks @phyleria

**Comment by ayan-joshi** [comment]
@phyleria hey phylis I had a doubt will this be counted as a contribution ?

**Comment by phyleria** [comment]
Hi @ayan-joshi 

For hacktoberfest yes. However, from our side, we will only be able to issue a badge for participation.
