### ISSUE TITLE
Enhancement: Improving the "Go back to top" link on the README.MD

### ISSUE THREAD

**Issue by Artemiskgg1** [Chimoney/chimoney-community-projects#445]
### Description

The current "go back to top" on the end of the README is just a Hyperlink.
We can give is a better UI for better user experience

### Screenshots

![image](https://github.com/user-attachments/assets/71b4faf5-c0b1-4979-95fe-7f413b3b8e02)

### Ready to Work?

- [X] I want to work on this enhancement

**Comment by AbrahamAlgorithm** [comment]
assign this to me

**Comment by phyleria** [comment]
Sure @AbrahamAlgorithm 

Go ahead ✅
