### ISSUE TITLE
Enhancement: Adding Bangla as a language in the README

### ISSUE THREAD

**Issue by faria-karim-porna** [Chimoney/chimoney-community-projects#449]
### Description

**Issue:** Not having Bangla in the README might make it less accessible for people who speak Bangla as their first language.

**Reason to fix:** Adding Bangla would help more people feel included and make the project easier for them to follow. It could also bring more interest and support from the Bangla-speaking community.

### Screenshots

![bangla-readme](https://github.com/user-attachments/assets/188fc36c-51c8-48ba-899f-7dc45815240a)

### Ready to Work?

- [X] I want to work on this enhancement

**Comment by faria-karim-porna** [comment]
@uchibeke @phyleria would you please assign this issue to me and label it as hacktoberfest?

**Comment by naaa760** [comment]
Hello @faria-karim-porna  :)
I want to work on this issue!

**Comment by faria-karim-porna** [comment]
Hi @phyleria would you please label it as hacktoberfest?

**Comment by phyleria** [comment]
Done @faria-karim-porna ✅

**Comment by naaa760** [comment]
I have created a pull request for this issue!
Thankyou!

**Comment by phyleria** [comment]
Hi @faria-karim-porna, I believe you were also working on this. Would you like me to go ahead and review @naaa760's PR?

**Comment by faria-karim-porna** [comment]
Hi @phyleria, Yes, I was working on this as well. Please feel free to go ahead and review the PR. After it’s merged, could I have permission to make additional changes if needed for further improvement?

**Comment by phyleria** [comment]
Sure, I have merged it, you can go ahead ✅
