### ISSUE TITLE
SMS Redeem URL formatted incorrectly.

### ISSUE THREAD

**Issue by tobiadiks** [Chimoney/chimoney-community-projects#46]
The redeeming link sent via SMS is not formated correctly, 
Here's a sample SMS

```
You've got 2000 
      Redeem below: https://dash.chimoney.io/redeem?chi=cbba813f-7435-44c4-9c75-4ef0a1a7dea4!
```
This URL has "!" at the end which when clicked cause an infinite loading screen.
The formated URL should be 

`https://dash.chimoney.io/redeem?chi=cbba813f-7435-44c4-9c75-4ef0a1a7dea4`

**Comment by adi-uchiha** [comment]
I would like to work on this

**Comment by uchibeke** [comment]
Hi @adi-uchiha this is in a private repo

@Regedit-msc let's fix, please

@tobiadiks thanks for catching it. This will count towards you contribution when fixed

**Comment by Regedit-msc** [comment]
> Hi @adi-uchiha this is in a private repo
> 
> @Regedit-msc let's fix, please
> 
> @tobiadiks thanks for catching it. This will count towards you contribution when fixed

👍🏾

**Comment by Regedit-msc** [comment]
Fixed!

**Comment by tobiadiks** [comment]
Thank you @uchibeke @Regedit-msc for the fix.
