### ISSUE TITLE
Enhancement: Updating Bangla documentation in the README

### ISSUE THREAD

**Issue by faria-karim-porna** [Chimoney/chimoney-community-projects#468]
### Description

**Issue:** The Bangla documentation might not be clear or concise, making it hard for readers to grasp the content. Links mentioned in the document is not navigating to the correct sub section of the document

**Reason to fix:** Well-written documentation can encourage more Bangla-speaking users to adopt and contribute to the project. Ensure that all referenced links are correct and point to valid sub sections.

### Screenshots

![bangla-issue](https://github.com/user-attachments/assets/2241c7fa-f6ac-49de-83ce-da5500b2ec0d)

### Ready to Work?

- [X] I want to work on this enhancement

**Comment by faria-karim-porna** [comment]
Hi @phyleria, would you please assign this to me and label it as hacktoberfest. It will take at most three hours to finish the task. So I believe I can complete it before the hacktoberfest finishes.

**Comment by phyleria** [comment]
Done @faria-karim-porna ✅

**Comment by faria-karim-porna** [comment]
Hi @phyleria, would you please merge the PR and label the issue as hacktoberfest.
