### ISSUE TITLE
Adding Hover Effect to all the Buttons

### ISSUE THREAD

**Issue by Kritika30032002** [Chimoney/chimoney-community-projects#54]
Adding Hover Effect to all the Buttons

Assign this to me!!

**Comment by Fadahunsiseyi** [comment]
can you please assign this to me?

**Comment by Fadahunsiseyi** [comment]
can you please assign this to me?

**Comment by Fadahunsiseyi** [comment]
can you please assign this to me?

**Comment by uchibeke** [comment]
Hi, which of our websites is this issue for?

**Comment by Kritika30032002** [comment]
> Hi, which of our websites is this issue for?

https://chimoney.io/     this one

**Comment by swarajmhatre** [comment]
CAN YOU PLEASE ASSIGN THIS ISSUE TO ME

**Comment by uchibeke** [comment]
The website is not in a public repo
