### ISSUE TITLE
Add drop-down for gift card and mobile money for map.

### ISSUE THREAD

**Issue by tobiadiks** [Chimoney/chimoney-community-projects#64]
Add a drop-down for gift cards showing the supported cards for specific countries.

Add a drop-down for mobile money.

Fix the category order with Product and Gift cards coming last in this order.

**Comment by uchibeke** [comment]
Product and crypto come last in the order 

also, you’re adding a Gift card and Mobile Money Category

**Comment by tobiadiks** [comment]
Noted.

**Comment by uchibeke** [comment]
@tobiadiks how's this going

**Comment by tobiadiks** [comment]
Going good, should push it before tomorrow evening.
