### ISSUE TITLE
Create a mobile (Flutter) Application that leverages the `Pay With Wallet` functionality on the ChiSpend widget to make an airtime payout.

### ISSUE THREAD

**Issue by Regedit-msc** [Chimoney/chimoney-community-projects#7]
What should your pr include?

- A video show casing the flow till payout.
-  Screenshots/apk
## TIPS AND REFERENCES:
- The javaScript channel  for the [webview](https://pub.dev/packages/webview_flutter) is `ChiSpendChannel`.
- [Get api key](https://github.com/Chimoney/chimoney-api-community-projects#get-started) 
- [More info](https://github.com/Chimoney/chispend-integration-examples/blob/main/web/README.md)

**Comment by Mujhtech** [comment]
Assign this to me @Regedit-msc

**Comment by AbhishekTiwari23** [comment]
I love to work on this. Please assign.

**Comment by uchibeke** [comment]
Hi @Mujhtech  and @AbhishekTiwari23 assigned to both of you

Feel free to implement your own versions of the same thing

**Comment by dynamic-Somto** [comment]
Hello @uchibeke @Regedit-msc I would love to take it up too
