### ISSUE TITLE
Propose a new copy for the chispend.com website.

### ISSUE THREAD

**Issue by Regedit-msc** [Chimoney/chimoney-community-projects#9]
What your pr is expected to include?

- A readme file stating what section, the old copy and the newly proposed copy.

**Comment by Zubair-12** [comment]
Hi, @Regedit-msc can you explain more?

**Comment by Zubair-12** [comment]
Sure dear, @Regedit-msc I want to work on this. Can you assign me?

**Comment by Khadeeejah** [comment]
hello @Regedit-msc has this been done already ? if not can i make a pr, i just did it , and secondly we cant have another README.md file
 can i just rename it to something like "proposition.md"

**Comment by Regedit-msc** [comment]
> hello @Regedit-msc has this been done already ? if not can i make a pr, i just did it , and secondly we cant have another README.md file
> can i just rename it to something like "proposition.md"

Submissions should be included in the [`submissions`](https://github.com/Chimoney/chimoney-community-projects/tree/main/submissions) folder. You can create a new folder in there and give it any name you see fit then include a  `markdown` file in it. Hope this provides more context?

**Comment by CyberGeni** [comment]
@Regedit-msc I also want to be assigned to this. can multiple people work on this? also one question, do i add all the proposed section changes in one PR or different PRs for different section changes?

**Comment by adeola-dev** [comment]
Hi @Regedit-msc , can multiple people work on this? I'd like to make a pr

**Comment by Regedit-msc** [comment]
Sorry for the late response. Yes multiple people can work on the pr!

**Comment by adeola-dev** [comment]
Ok, thanks👍
