### ISSUE TITLE
Add a 'Contributors section' to the README

### ISSUE THREAD

**Issue by phyleria** [Chimoney/chimoney-community-projects#92]
**Summary**: Create a section in the README that lists and acknowledges all project contributors.

**Idea Flow:** 

- Update the README with a list of contributors and their GitHub profiles.
- Make this automated in that a contributor is automatically added once their PR is merged

**Comment by Mithilesh-create** [comment]
I would like to work on this issue.

**Comment by phyleria** [comment]
Sure, assigning it to you now

**Comment by Liwei254** [comment]
the issue is partially solved

**Comment by phyleria** [comment]
What would you like to add @Liwei254 ?
