### ISSUE TITLE
Create Documentation for any SDK Implemented in our Developer API docs

### ISSUE THREAD

**Issue by phyleria** [Chimoney/chimoney-community-projects#93]
**Summary**: Generate comprehensive documentation for any SDK that has been implemented [here](https://chimoney.readme.io/reference/libraries-plugins#sdks) to assist developers in using it effectively.

**Idea Flow:** 

- Write clear and user-friendly documentation, including installation instructions and code examples.

**Comment by mynameissaraah** [comment]
Hi @phyleria, I would like this to be assigned to me to work on.

**Comment by phyleria** [comment]
Sure, go ahead.

**Comment by phyleria** [comment]
Which SDK would you like to work on?

**Comment by mynameissaraah** [comment]
The JavaScript SDK

**Comment by phyleria** [comment]
Unfortunately that issue has been taken already [here](https://github.com/Chimoney/chimoney-community-projects/issues/98)
I'll be closing this now.

You can pick another issue or create one on documentation and I'll assign it to you.
